export const translations = {
  en: {
    // Landing Page
    "AI Voice Coach": "Voice Coach",
    "Start Coaching": "Start Coaching", 
    "Your Personal AI Voice Coach": "Your Personal Voice Coach",
    "Master your speaking skills with real-time AI feedback. Perfect for interviews, presentations, language learning, and more.": "Master your speaking skills with real-time AI feedback. Perfect for interviews, presentations, language learning, and more.",
    "Try Free Session": "Try Free Session",
    "Enhance Your Speaking Skills": "Enhance Your Speaking Skills",
    "Real-time Analysis": "Real-time Analysis",
    "Get instant feedback on your speech patterns, tone, and delivery with advanced AI processing.": "Get instant feedback on your speech patterns, tone, and delivery with advanced AI processing.",
    "Guided Practice": "Guided Practice", 
    "Choose from various coaching scenarios including interview prep, presentations, and language practice.": "Choose from various coaching scenarios including interview prep, presentations, and language practice.",
    "Smart Insights": "Smart Insights",
    "Receive personalized improvement suggestions and track your progress over time.": "Receive personalized improvement suggestions and track your progress over time.",
    "Ready to Improve Your Speaking Skills?": "Ready to Improve Your Speaking Skills?",
    "Begin Your Journey": "Begin Your Journey",
    "All rights reserved.": "All rights reserved.",
    "Made by": "Made by",
    "Kwak Dooil": "Kwak Dooil",
    "Local User": "Local User",
    
    // Dashboard
    "My Workspace": "My Workspace",
    "Welcome back": "Welcome back",
    "Profile": "Profile",
    
    // Coaching Options
    "Topic Base Lecture": "Topic Based Lecture",
    "Mock Interview": "Mock Interview", 
    "Ques Ans Prep": "Q&A Preparation",
    "Learn Language": "Learn Language",
    "Meditation": "Meditation",
    "Voice Recording": "Voice Recording",
    
    // Common
    "Connect": "Connect",
    "Disconnect": "Disconnect",
    "Connected...": "Connected...",
    "Disconnected!": "Disconnected!",
    "Loading...": "Loading...",
    "Send": "Send",
    "Sign Out": "Sign Out",
    
    // Dialog texts
    "Enter a topic to master your skills in": "Enter a topic to master your skills in",
    "Enter your topic here...": "Enter your topic here...",
    "Select your coaching expert": "Select your coaching expert",
    "Cancel": "Cancel",
    "Next": "Next",
    "Generate Feedback/Notes": "Generate Feedback/Notes",
    "Feedback/Notes Saved!": "Feedback/Notes Saved!",
    "Internal server error, Try again!": "Internal server error, Try again!",
    
    // Credits component
    "Token Usage": "Token Usage",
    "Current Plan": "Current Plan",
    "Free Plan": "Free Plan",
    "Pro Plan": "Pro Plan",
    "Tokens": "Tokens", 
    "Upgrade": "Upgrade",
    "$10/Month": "$10/Month",
    "Month": "Month",
    "Upgrade $10": "Upgrade $10",
    
    // History and Feedback components
    "Your Previous Lectures": "Your Previous Lectures",
    "You don't have any previous lectures": "You don't have any previous lectures",
    "Feedback": "Feedback",
    "You don't have any previous feedback": "You don't have any previous feedback",
    "View Notes": "View Notes",
    "View Feedback": "View Feedback",
    
    // Advanced Recorder
    "고급 음성 녹음기": "Advanced Voice Recorder",
    "녹음 중...": "Recording...",
    "녹음 완료": "Recording Complete", 
    "녹음 대기": "Ready to Record",
    "중지": "Stop",
    "녹음": "Record",
    "재설정": "Reset",
    "다운로드": "Download",
    "음성 사용하기": "Use This Recording",
    "길이": "Duration",
    "품질": "Quality",
    
    // Misc texts
    "Redirecting to dashboard...": "Redirecting to dashboard...",
    "Create Next App": "Create Next App",
    "Generated by create next app": "Generated by create next app"
  },
  ko: {
    // Landing Page  
    "AI Voice Coach": "음성 코치",
    "Start Coaching": "코칭 시작하기",
    "Your Personal AI Voice Coach": "당신만의 개인 음성 코치",
    "Master your speaking skills with real-time AI feedback. Perfect for interviews, presentations, language learning, and more.": "실시간 AI 피드백으로 말하기 실력을 향상시키세요. 면접, 발표, 언어 학습 등에 완벽합니다.",
    "Try Free Session": "무료 체험하기",
    "Enhance Your Speaking Skills": "말하기 실력 향상하기",
    "Real-time Analysis": "실시간 분석",
    "Get instant feedback on your speech patterns, tone, and delivery with advanced AI processing.": "고급 AI 처리로 말하기 패턴, 톤, 전달력에 대한 즉각적인 피드백을 받으세요.",
    "Guided Practice": "가이드 연습",
    "Choose from various coaching scenarios including interview prep, presentations, and language practice.": "면접 준비, 발표, 언어 연습 등 다양한 코칭 시나리오 중에서 선택하세요.",
    "Smart Insights": "스마트 인사이트",
    "Receive personalized improvement suggestions and track your progress over time.": "개인맞춤 개선 제안을 받고 시간에 따른 진전을 추적하세요.",
    "Ready to Improve Your Speaking Skills?": "말하기 실력을 향상시킬 준비가 되셨나요?",
    "Begin Your Journey": "여정 시작하기",
    "All rights reserved.": "모든 권리 보유.",
    "Made by": "제작자",
    "Kwak Dooil": "곽두일",
    "Local User": "로컬 사용자",
    
    // Dashboard
    "My Workspace": "내 워크스페이스",
    "Welcome back": "다시 오신 것을 환영합니다",
    "Profile": "프로필",
    
    // Coaching Options
    "Topic Base Lecture": "주제별 강의",
    "Mock Interview": "모의 면접",
    "Ques Ans Prep": "질문답변 준비",
    "Learn Language": "언어 학습", 
    "Meditation": "명상",
    "Voice Recording": "음성 녹음",
    
    // Common
    "Connect": "연결",
    "Disconnect": "연결 해제",
    "Connected...": "연결됨...",
    "Disconnected!": "연결 해제됨!",
    "Loading...": "로딩 중...",
    "Send": "보내기",
    "Sign Out": "로그아웃",
    
    // Dialog texts
    "Enter a topic to master your skills in": "기술을 연마할 주제를 입력하세요",
    "Enter your topic here...": "여기에 주제를 입력하세요...",
    "Select your coaching expert": "코칭 전문가를 선택하세요",
    "Cancel": "취소",
    "Next": "다음",
    "Generate Feedback/Notes": "피드백/노트 생성하기",
    "Feedback/Notes Saved!": "피드백/노트가 저장되었습니다!",
    "Internal server error, Try again!": "내부 서버 오류, 다시 시도해주세요!",
    
    // Credits component
    "Token Usage": "토큰 사용량",
    "Current Plan": "현재 플랜",
    "Free Plan": "무료 플랜",
    "Pro Plan": "프로 플랜",
    "Tokens": "토큰",
    "Upgrade": "업그레이드",
    "$10/Month": "월 10,000원",
    "Month": "월",
    "Upgrade $10": "10,000원 업그레이드",
    
    // History and Feedback components
    "Your Previous Lectures": "이전 강의 기록",
    "You don't have any previous lectures": "이전 강의 기록이 없습니다",
    "Feedback": "피드백",
    "You don't have any previous feedback": "이전 피드백이 없습니다",
    "View Notes": "노트 보기",
    "View Feedback": "피드백 보기",
    
    // Advanced Recorder
    "고급 음성 녹음기": "고급 음성 녹음기",
    "녹음 중...": "녹음 중...",
    "녹음 완료": "녹음 완료",
    "녹음 대기": "녹음 대기",
    "중지": "중지",
    "녹음": "녹음",
    "재설정": "재설정", 
    "다운로드": "다운로드",
    "음성 사용하기": "음성 사용하기",
    "길이": "길이",
    "품질": "품질",
    
    // Misc texts
    "Redirecting to dashboard...": "대시보드로 이동 중...",
    "Create Next App": "음성 코치",
    "Generated by create next app": "음성 연습을 위한 개인 코치 애플리케이션"
  }
};

export default translations;